# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import nlp_pb2 as nlp__pb2


class NLPServiceStub(object):
    """Missing associated documentation comment in .proto file"""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.AskQuestion = channel.unary_unary(
                '/nlp.NLPService/AskQuestion',
                request_serializer=nlp__pb2.AskQuestionRequest.SerializeToString,
                response_deserializer=nlp__pb2.AskQuestionResponse.FromString,
                )
        self.AskQuestions = channel.unary_unary(
                '/nlp.NLPService/AskQuestions',
                request_serializer=nlp__pb2.AskQuestionsRequest.SerializeToString,
                response_deserializer=nlp__pb2.AskQuestionsResponse.FromString,
                )


class NLPServiceServicer(object):
    """Missing associated documentation comment in .proto file"""

    def AskQuestion(self, request, context):
        """Missing associated documentation comment in .proto file"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AskQuestions(self, request, context):
        """Missing associated documentation comment in .proto file"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_NLPServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'AskQuestion': grpc.unary_unary_rpc_method_handler(
                    servicer.AskQuestion,
                    request_deserializer=nlp__pb2.AskQuestionRequest.FromString,
                    response_serializer=nlp__pb2.AskQuestionResponse.SerializeToString,
            ),
            'AskQuestions': grpc.unary_unary_rpc_method_handler(
                    servicer.AskQuestions,
                    request_deserializer=nlp__pb2.AskQuestionsRequest.FromString,
                    response_serializer=nlp__pb2.AskQuestionsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'nlp.NLPService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class NLPService(object):
    """Missing associated documentation comment in .proto file"""

    @staticmethod
    def AskQuestion(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/nlp.NLPService/AskQuestion',
            nlp__pb2.AskQuestionRequest.SerializeToString,
            nlp__pb2.AskQuestionResponse.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def AskQuestions(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/nlp.NLPService/AskQuestions',
            nlp__pb2.AskQuestionsRequest.SerializeToString,
            nlp__pb2.AskQuestionsResponse.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)
