apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: {{ include "nlpservice.fullname" . }}
  labels:
    {{- include "nlpservice.labels" . | nindent 4 }}
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      {{- include "nlpservice.selectorLabels" . | nindent 6 }}
